"""update_enquiry_fields

Revision ID: be92b034908f
Revises: c5d1cab99a9d
Create Date: 2025-09-16 17:57:16.344606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be92b034908f'
down_revision = 'c5d1cab99a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('product_category', sa.String(), nullable=False, server_default=''))
    op.add_column('enquiries', sa.Column('child_category', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'enquiries', ['email'])
    op.drop_column('enquiries', 'beer_styles')
    op.drop_column('enquiries', 'product_categories')
    op.drop_index('uniq_active_questionnaire_per_category', table_name='questionnaires', postgresql_where="((status = 'PUBLISHED'::questionnairestatus) AND (is_active = true) AND (deleted_at IS NULL))")
    op.create_index('uniq_active_questionnaire_per_category', 'questionnaires', ['category_code'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED' AND is_active = true AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_active_questionnaire_per_category', table_name='questionnaires', postgresql_where=sa.text("status = 'PUBLISHED' AND is_active = true AND deleted_at IS NULL"))
    op.create_index('uniq_active_questionnaire_per_category', 'questionnaires', ['category_code'], unique=True, postgresql_where="((status = 'PUBLISHED'::questionnairestatus) AND (is_active = true) AND (deleted_at IS NULL))")
    op.add_column('enquiries', sa.Column('product_categories', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('enquiries', sa.Column('beer_styles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enquiries', type_='unique')
    op.drop_column('enquiries', 'child_category')
    op.drop_column('enquiries', 'product_category')
    # ### end Alembic commands ###
