"""add_enquiry_table

Revision ID: c5d1cab99a9d
Revises: 13665e148b42
Create Date: 2025-09-16 17:45:28.010861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d1cab99a9d'
down_revision = '13665e148b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', name='enquirystatus'), nullable=False),
    sa.Column('venue_type', sa.String(), nullable=False),
    sa.Column('venue_style', sa.String(), nullable=True),
    sa.Column('product_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('beer_styles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('legal_entity_name', sa.String(), nullable=True),
    sa.Column('trading_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('acn', sa.String(), nullable=True),
    sa.Column('liquor_license_number', sa.String(), nullable=True),
    sa.Column('outlet_type', sa.String(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('business_city', sa.String(), nullable=True),
    sa.Column('business_state', sa.String(), nullable=True),
    sa.Column('business_postal_code', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('unit_number', sa.String(), nullable=True),
    sa.Column('street_number', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('referral_sourced', sa.String(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('outlet_style', sa.String(), nullable=True),
    sa.Column('apply_commercial_credit_terms', sa.Boolean(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.UUID(), nullable=True),
    sa.Column('questionnaire_version', sa.Integer(), nullable=True),
    sa.Column('questionnaire_title', sa.String(), nullable=True),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salesforce_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enquiry_created_at', 'enquiries', ['created_at'], unique=False)
    op.create_index('idx_enquiry_email', 'enquiries', ['email'], unique=False)
    op.create_index('idx_enquiry_status', 'enquiries', ['status'], unique=False)
    op.create_index('idx_enquiry_venue_style', 'enquiries', ['venue_style'], unique=False)
    op.create_index('idx_enquiry_venue_type', 'enquiries', ['venue_type'], unique=False)
    op.create_index(op.f('ix_enquiries_id'), 'enquiries', ['id'], unique=False)
    op.drop_index('uniq_active_questionnaire_per_category', table_name='questionnaires', postgresql_where="((status = 'PUBLISHED'::questionnairestatus) AND (is_active = true) AND (deleted_at IS NULL))")
    op.create_index('uniq_active_questionnaire_per_category', 'questionnaires', ['category_code'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED' AND is_active = true AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_active_questionnaire_per_category', table_name='questionnaires', postgresql_where=sa.text("status = 'PUBLISHED' AND is_active = true AND deleted_at IS NULL"))
    op.create_index('uniq_active_questionnaire_per_category', 'questionnaires', ['category_code'], unique=True, postgresql_where="((status = 'PUBLISHED'::questionnairestatus) AND (is_active = true) AND (deleted_at IS NULL))")
    op.drop_index(op.f('ix_enquiries_id'), table_name='enquiries')
    op.drop_index('idx_enquiry_venue_type', table_name='enquiries')
    op.drop_index('idx_enquiry_venue_style', table_name='enquiries')
    op.drop_index('idx_enquiry_status', table_name='enquiries')
    op.drop_index('idx_enquiry_email', table_name='enquiries')
    op.drop_index('idx_enquiry_created_at', table_name='enquiries')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
