import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { PLHeader } from './components/ui/PL/PLHeader/PLHeader';
import { RootProvider } from './providers/RootProvider';

const indivisible = localFont({
  src: [
    {
      path: './fonts/indivisible-medium-webfont.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/indivisible-semibold-webfont.woff2',
      weight: '600',
      style: 'normal'
    }
  ]
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={indivisible.className}>
        <RootProvider>
          <PLHeader />
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
